travis:
  secure:
    BINSTAR_TOKEN: KuOJs9rAqZZ/UMTcKgTi2Qq3+SZvHNVzz/FqwEbbYqU05CHR0ikzcFVRRN7tBcjvCGFudmHkyFVYfvaKz/T5htJCtHxk1qLvIvUIAWnAg3Oh/MeAq0E8pveIuVYJSi3xld17hI3Jd2F2OmQlDE4I6edD0Qj5Ucbkaxq2Hl3sFz/ShJ0NaEohM33NKhWMHisiF/5ANT8eZ5fzqfworP2H0Gnn5ZuL8HpmLIXX4V6bFGmc+FbXhgXYURHOuAZgv4xUTtgpFsuZFwGcJxOo0gVWFmWewXqokiAEsseAgmu5UGaiKZqdsoSm0X3cAS08SNyzrFYTru/X0LMHK1UjcTQR81dnKsfPrXkpiSO0TyrPFFWExMQupYatkelLgDjEWW99sKfdAfxLLkE8opW5BmFFe/Eyqih7hZontLX+YWKEPOb7fBOaS3yRVfo5oNl5y/gtwBiZeDzBgiQitdgkLV5/7GEyUGS9oFVbMeidMjmSMYW4Zhwd5x6t1HkWDeHBKVXFqPNgeYJgwua3Q7/vtEHegxFmCVBOIAVt6rt7pOg5Fg35xVGmstOk/Vfl3fLHuPaesLQ9lGTd9EgT3ZxCynwLD18Bls1iFT9deRLevQ8OI9WsP4YMYLReE1dyC8NS35cGgGV/x5wJWT+FT31rTmot4X4ST+jZcAFJJrdWvostZA0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
